
export const REMOVE_ERRORS = 'REMOVE_ERRORS'
export const SET_LOADER = 'SET_LOADER'
export const CLOSE_LOADER = 'CLOSE_LOADER'
export const REDIRECT_TRUE= 'REDIRECT_TRUE'
export const REDIRECT_FALSE = 'REDIRECT_FALSE'
export const SET_MSG = 'SET_MSG'
export const REMOVE_MSG='REMOVE_MSG'
export const SET_POSTS = 'SET_POSTS';
export const SET_POST = 'SET_POST';
export const POST_REQUEST = 'POST_REQUEST';
export const POST_RESET = 'POST_RESET'
export const SET_UPDATE_ERRORS = 'SET_UPDATE_ERRORS';
export const RESET_UPDATE_ERRORS = 'RESET_UPDATE_ERRORS';
export const UPDATE_IMAGE_ERROR = 'UPDATE_IMAGE_ERROR';
export const RESET_UPDATE_IMAGE_ERROR = 'RESET_UPDATE_IMAGE_ERROR'; 
export const CREATE_ERRORS = 'CREATE_ERRORS';